### ISSUE TITLE
Fix rules for Windows

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/rules_iota#34]
- [x] yaml_test
- [x] prometheus_test
- [ ] boost_log_test
- [x] keccak_test
- [ ] argon2_and_sodium_test
- [x] libmicrohttpd_test
- [x] mbedtls_test
- [ ] iota_lib_cpp_test
- [x] libuv_test
- [ ] cppzmq_test

**Comment by bingyanglin** [comment]
Current errors:
**boost_log_test**: no  <langinfo.h>
**keccak_test**: undeclared inclusion(s) in rule '@keccak//:keccak_sponge_1600'
**argon2_and_sodium_test**: multiple definitions in libsodium.a
**libmicrohttpd_test**: lacks <sys/eventfd.h>
**libuv_test**: undefined reference to `__imp_GetUserProfileDirectoryW'
**cppzmq_test**: No netdb.h
**iota_lib_cpp_test**: undeclared inclusion(s) in rule '@keccak//:keccak_sponge_1600'

**Comment by bingyanglin** [comment]
Current errors:
boost_log_test: no <langinfo.h>
argon2_and_sodium_test: multiple definitions in libsodium.a
cppzmq_test: No netdb.h
iota_lib_cpp_test: 
`$ bazel build -c dbg //:iota_lib_cpp_test --test_output=all --cpu=x64_windows --compiler=mingw-gcc
Loading:
Loading: 0 packages loaded
INFO: Build option --python_path has changed, discarding analysis cache.
Analyzing: target //:iota_lib_cpp_test (0 packages loaded, 0 targets configured)
Analyzing: target //:iota_lib_cpp_test (1 packages loaded, 27 targets configured)
Analyzing: target //:iota_lib_cpp_test (1 packages loaded, 27 targets configured)
DEBUG: Rule 'iota_lib_cpp' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1560426953 +0200"
DEBUG: Call stack for the definition of repository 'iota_lib_cpp' which is a new_git_repository (rule definition at C:/users/chi/_bazel_chi/4kfuida6/external/bazel_tools/tools/build_defs/repo/git.bzl:239:22):
 - C:/users/chi/_bazel_chi/4kfuida6/external/rules_iota/internal/repositories.bzl:296:5
 - C:/users/chi/_bazel_chi/4kfuida6/external/rules_iota/internal/repositories.bzl:342:5
 - C:/users/chi/_bazel_chi/4kfuida6/external/rules_iota/defs.bzl:5:5
 - D:/github_iota/my_rules_iota/rules_iota/tests/WORKSPACE:8:1
Analyzing: target //:iota_lib_cpp_test (2 packages loaded, 278 targets configured)
Analyzing: target //:iota_lib_cpp_test (2 packages loaded, 278 targets configured)
INFO: Analyzed target //:iota_lib_cpp_test (3 packages loaded, 4637 targets configured).
INFO: Found 1 target...
[0 / 9] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[6 / 23] Compiling external/boost/libs/regex/src/fileiter.cpp; 2s local ... (8 actions, 5 running)
[12 / 25] Compiling external/boost/libs/regex/src/regex_traits_defaults.cpp; 2s local ... (8 actions, 4 running)
[132 / 143] Compiling external/boost/libs/regex/src/cregex.cpp; 3s local ... (8 actions, 4 running)
[135 / 146] Compiling external/boost/libs/regex/src/cregex.cpp; 7s local ... (8 actions, 4 running)
[141 / 151] Compiling external/iota_lib_cpp/source/api/core.cpp; 7s local ... (8 actions, 4 running)
[149 / 159] Compiling external/iota_lib_cpp/source/api/requests/check_consistency.cpp; 2s local ... (8 actions, 4 running)
[163 / 173] Compiling external/iota_lib_cpp/source/api/extended.cpp; 3s local ... (8 actions, 4 running)
[175 / 185] Compiling external/iota_lib_cpp/source/api/responses/get_transactions_to_approve.cpp; 1s local ... (8 actions, 4 running)
[208 / 215] Compiling external/iota_lib_cpp/source/api/responses/remove_neighbors.cpp; 1s local ... (5 actions running)
ERROR: D:/github_iota/my_rules_iota/rules_iota/tests/BUILD:124:1: Linking of rule '//:iota_lib_cpp_test' failed (Exit 1): gcc failed: error executing command
  cd C:/users/chi/_bazel_chi/4kfuida6/execroot/__main__
  SET PATH=c:/msys64/mingw64/bin
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
  c:/msys64/mingw64/bin/gcc -o bazel-out/x64_windows-dbg/bin/iota_lib_cpp_test.exe bazel-out/x64_windows-dbg/bin/_objs/iota_lib_cpp_test/iota_lib_cpp_test.o bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a bazel-out/x64_windows-dbg/bin/external/boost/libchrono.a bazel-out/x64_windows-dbg/bin/external/boost/libcontainer.a bazel-out/x64_windows-dbg/bin/external/boost/libregex.a bazel-out/x64_windows-dbg/bin/external/boost/libexception.a bazel-out/x64_windows-dbg/bin/external/boost/libsystem.a bazel-out/x64_windows-dbg/bin/external/keccak/libkeccak.a bazel-out/x64_windows-dbg/bin/external/keccak/libkeccak_sponge_1600.a bazel-out/x64_windows-dbg/bin/external/keccak/libsnp_1600_reference.a -lcrypto -lssl -lstdc++
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/x64_windows-dbg/bin/_objs/iota_lib_cpp_test/iota_lib_cpp_test.o:iota_lib_cpp_test.cc:(.text$_ZN5boost4asio6detail17winsock_init_base7startupERNS2_4dataEhh[_ZN5boost4asio6detail17winsock_init_base7startupERNS2_4dataEhh]+0x74): undefined reference to `__imp_WSAStartup'
bazel-out/x64_windows-dbg/bin/_objs/iota_lib_cpp_test/iota_lib_cpp_test.o:iota_lib_cpp_test.cc:(.text$_ZN5boost4asio6detail17winsock_init_base7cleanupERNS2_4dataE[_ZN5boost4asio6detail17winsock_init_base7cleanupERNS2_4dataE]+0x35): undefined reference to `__imp_WSACleanup'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops16clear_last_errorEv[_ZN5boost4asio6detail10socket_ops16clear_last_errorEv]+0x10): undefined reference to `__imp_WSASetLastError'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE]+0xab): undefined reference to `__imp_closesocket'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE]+0x148): undefined reference to `__imp_ioctlsocket'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops5closeEyRhbRNS_6system10error_codeE]+0x16c): undefined reference to `__imp_closesocket'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops8shutdownEyiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops8shutdownEyiRNS_6system10error_codeE]+0x43): undefined reference to `__imp_shutdown'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops4recvEyP7_WSABUFyiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops4recvEyP7_WSABUFyiRNS_6system10error_codeE]+0x67): undefined reference to `__imp_WSARecv'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops4sendEyPK7_WSABUFyiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops4sendEyPK7_WSABUFyiRNS_6system10error_codeE]+0x65): undefined reference to `__imp_WSASend'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops6socketEiiiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops6socketEiiiRNS_6system10error_codeE]+0x42): undefined reference to `__imp_WSASocketW'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops6socketEiiiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops6socketEiiiRNS_6system10error_codeE]+0x99): undefined reference to `__imp_setsockopt'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops9poll_readEyhiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops9poll_readEyhiRNS_6system10error_codeE]+0x18c): undefined reference to `__imp_select'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops10poll_writeEyhiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops10poll_writeEyhiRNS_6system10error_codeE]+0x18b): undefined reference to `__imp_select'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops12poll_connectEyiRNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops12poll_connectEyiRNS_6system10error_codeE]+0x1e1): undefined reference to `__imp_select'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops24translate_addrinfo_errorEi[_ZN5boost4asio6detail10socket_ops24translate_addrinfo_errorEi]+0x1c4): undefined reference to `__imp_WSAGetLastError'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops11getaddrinfoEPKcS4_RK8addrinfoPPS5_RNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops11getaddrinfoEPKcS4_RK8addrinfoPPS5_RNS_6system10error_codeE]+0x81): undefined reference to `__imp_getaddrinfo'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops12freeaddrinfoEP8addrinfo[_ZN5boost4asio6detail10socket_ops12freeaddrinfoEP8addrinfo]+0x13): undefined reference to `__imp_freeaddrinfo'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops13error_wrapperIyEET_S4_RNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops13error_wrapperIyEET_S4_RNS_6system10error_codeE]+0x21): undefined reference to `__imp_WSAGetLastError'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops13error_wrapperIiEET_S4_RNS_6system10error_codeE[_ZN5boost4asio6detail10socket_ops13error_wrapperIiEET_S4_RNS_6system10error_codeE]+0x20): undefined reference to `__imp_WSAGetLastError'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops12call_connectIiEEiMNS2_6msghdrET_yPK8sockaddry[_ZN5boost4asio6detail10socket_ops12call_connectIiEEiMNS2_6msghdrET_yPK8sockaddry]+0x2f): undefined reference to `__imp_connect'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops15call_setsockoptIiEEiMNS2_6msghdrET_yiiPKvy[_ZN5boost4asio6detail10socket_ops15call_setsockoptIiEEiMNS2_6msghdrET_yiiPKvy]+0x3e): undefined reference to `__imp_setsockopt'
bazel-out/x64_windows-dbg/bin/external/iota_lib_cpp/libiota_lib_cpp.a(core.o):core.cpp:(.text$_ZN5boost4asio6detail10socket_ops15call_getsockoptIiEEiMNS2_6msghdrET_yiiPvPy[_ZN5boost4asio6detail10socket_ops15call_getsockoptIiEEiMNS2_6msghdrET_yiiPvPy]+0x40): undefined reference to `__imp_getsockopt'
collect2.exe: error: ld returned 1 exit status
Target //:iota_lib_cpp_test failed to build
INFO: Elapsed time: 65.242s, Critical Path: 23.01s
INFO: 79 processes: 79 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
`

**Comment by oopsmonk** [comment]
* libzmq doesn't support Windows. 
* the errors of iota_lib_cpp_test are caused by boost.
